repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: generate-go-docs
        name: generate-go-docs
        entry: ./scripts/hooks/generate-go-docs.sh
        language: system
      - id: generate-swagger-docs
        name: generate-swagger-docs
        entry: ./scripts/hooks/generate-swagger-docs.sh
        language: system
