version: "2.2"
services:
  models:
    image: tensorflow/serving
    container_name: models
    networks:
      - be-network
    volumes:
      - ./models/universal-encoder:/models/universal_encoder
    environment:
      MODEL_NAME: "universal_encoder"

  backend:
    image: api-scout-backend:latest
    container_name: backend
    networks:
      - be-network
    ports:
      - "8080:8080"
networks:
  be-network:
    driver: bridge
