basePath: /api/v1
definitions:
  models.EmbeddingRequest:
    properties:
      filters:
        type: string
      fragment:
        type: string
    type: object
  models.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: Bad Request
        type: string
    type: object
  models.MongoResponse:
    properties:
      apiVersion:
        $ref: '#/definitions/models.Version'
      apiVersionAlt1:
        type: string
      apiVersionAlt2:
        type: string
      commits:
        type: integer
      id:
        type: integer
      latest:
        type: boolean
      mongoId:
        type: string
      name:
        type: string
      nameAlt:
        type: string
      oastype:
        type: string
      oasversion:
        $ref: '#/definitions/models.Version'
      source:
        type: string
      sourceAlt1:
        type: string
      sourceAlt2:
        type: string
    type: object
  models.MongoResponseWithApi:
    properties:
      metadata:
        $ref: '#/definitions/models.MongoResponse'
      specification:
        type: string
    type: object
  models.SpecificationBackend:
    additionalProperties: true
    type: object
  models.SpecificationsRequest:
    properties:
      specifications:
        items:
          $ref: '#/definitions/models.SpecificationBackend'
        type: array
    type: object
  models.Version:
    properties:
      build:
        type: string
      major:
        type: integer
      minor:
        type: integer
      patch:
        type: integer
      prerelease:
        type: string
      raw:
        type: string
      valid:
        type: boolean
    type: object
info:
  contact: {}
  description: This is the backend for the API Scout platform.
  title: API Scout
  version: "1.0"
paths:
  /search:
    post:
      consumes:
      - application/json
      description: Retrieve OpenAPI specifications matching the given query
      parameters:
      - description: Search query
        in: body
        name: fragment
        required: true
        schema:
          $ref: '#/definitions/models.EmbeddingRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HTTPError'
      summary: Search OpenAPI specifications
      tags:
      - search
  /specification:
    post:
      consumes:
      - application/json
      description: Insert new OpenAPI specifications in the database.
      parameters:
      - description: New Specifications
        in: body
        name: specifications
        required: true
        schema:
          $ref: '#/definitions/models.SpecificationsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.HTTPError'
      summary: Insert OpenAPI specifications
      tags:
      - specification
  /specification/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve a specific OpenAPI specification's content given a valid
        ID
      parameters:
      - description: Specification ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.MongoResponseWithApi'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.HTTPError'
      summary: Get OpenAPI specification
      tags:
      - specification
swagger: "2.0"
