basePath: /api/v1
info:
  contact: {}
  description: This is the backend for the API Scout platform.
  title: API Scout
  version: "1.0"
paths:
  /search:
    post:
      consumes:
      - application/json
      description: retrieve OpenAPI specifications matching the given query
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Search OpenAPI specifications
      tags:
      - search
swagger: "2.0"
