name: Test and Deploy Backend

on: [ push ]

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: |
          go install gotest.tools/gotestsum@latest
          go get ./...

      - name: Build
        run: go build -o ./main ./app

      - name: Run tests
        run: gotestsum --hide-summary=skipped ./app/tests/... > tests-result.txt

      - name: Upload tests result
        uses: actions/upload-artifact@v4
        with:
          name: tests-result
          path: tests-result.txt

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: contains('
      refs/heads/dev
      refs/heads/main
      ', github.ref)
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: edoriggio/api-scout

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            "GIN_MODE=release"
            "MODELS_HOST=models"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
